### ISSUE TITLE
Exporting bordered assets

### ISSUE THREAD

**Issue by designbyjm** [GeertWille/sketch-export-assets#11]
First off, you have to export the asset vs the artboard. This then causes an issue with any bordered assets. 

Example: bucketloads-1.png is the artboard with assets on it.
![bucketloads-1](https://cloud.githubusercontent.com/assets/1541841/6921044/37e7c3b0-d790-11e4-9cf7-7f0d2fc7e429.png)

Example: bucketloads-2.png shows the artboard with the asset selected and you'll see that the coverage area is inside of the bordered area. (i.e. the bordered asset has "outside" borders vs "inside").
![bucketloads-2](https://cloud.githubusercontent.com/assets/1541841/6921059/52dce416-d790-11e4-89c7-fd015c45e65f.png)

**Comment by AndreasBackx** [comment]
+1 having the same problem.

**Comment by GeertWille** [comment]
@designbyjm, can you provide me a sample sketch file?

**Comment by akoskinen** [comment]
https://www.dropbox.com/s/h3swx4nuxomz05y/border_clipping.sketch?dl=0
Here's an example file. There is a simple circle with a border. Just run your plugin on the circle and you'll see the issue with the border getting clipped. Of course we could all force ourselves to always use borders set to "inside", but that's not really what you'd call a solution.
