### ISSUE TITLE
Exporting drop shadow

### ISSUE THREAD

**Issue by martinboerma** [GeertWille/sketch-export-assets#12]
Hi,

Great plugin. I use it a lot. Thanks for that!!

The plugin seems to crop the object based on it's transform handles. The result is cropped drop shadows.

Here's an example;

![image](https://cloud.githubusercontent.com/assets/11924339/7115390/9ab44ace-e1e8-11e4-9fd0-2327b5b4cbb6.png)

Cheers
Martin

**Comment by GeertWille** [comment]
Is alse fixed after fixing #11 ...
