### ISSUE TITLE
Filenames of output files are not android resource friendly.

### ISSUE THREAD

**Issue by magillus** [GeertWille/sketch-export-assets#13]
Is it possible to modify output filenames to match Java identifier restrictions.
Common for android are:
-start from a letter and no spaces allowed, 
-only "_" (underline) character allowed from special characters
-all lowercase characters.

**Comment by GeertWille** [comment]
When there is a space in front of the layer name instead of changing the name to _layer_name.png just remove the first character if it's a space... Same for last character, so basically trim the layer name first.

**Comment by GeertWille** [comment]
Also make sure [this issue](https://github.com/GeertWille/sketch-export-assets/issues/15) is fixed...

**Comment by GeertWille** [comment]
Thanks!
