### ISSUE TITLE
Why do I export png, naming front more words "undefined"

### ISSUE THREAD

**Issue by skalaloo** [GeertWille/sketch-export-assets#15]
？

**Comment by GeertWille** [comment]
It's not clear to me what you are reporting... Can you be more in depth please?

**Comment by skalaloo** [comment]
Sorry, my English is too bad :(

this is what i named [image: 内嵌图片 1]     and... [image: 内嵌图片 2]

what is it mean “underfined” ?


2015-05-08 14:28 GMT+08:00 Geert Wille <notifications@github.com>:

**Comment by GeertWille** [comment]
Can you link to screenshots?

**Comment by skalaloo** [comment]
I am back to you in GMAIL, ah, the picture was gone
![1](https://cloud.githubusercontent.com/assets/12291174/7532768/81801be6-f59d-11e4-89dd-e578a96dde55.png)
![2](https://cloud.githubusercontent.com/assets/12291174/7532769/8191bb80-f59d-11e4-9a83-bad309830ad0.png)

**Comment by GeertWille** [comment]
Can you pull the new version and try again?

**Comment by skalaloo** [comment]
that is OK! ilove u bro XD
