### ISSUE TITLE
Android: Allow for MIPMAP export

### ISSUE THREAD

**Issue by ened** [GeertWille/sketch-export-assets#17]
Given I want to export MIPMAP files (as outlined in https://androidbycode.wordpress.com/2015/02/14/goodbye-launcher-drawables-hello-mipmaps/)

Then I need to manually export the files using this plugin and place the icons in the mipmap folder in another step.

Is there a way to add a option for exporting into mipmap folders directly? (the semantics are the same, a in `mipmap-hdpi`, `mipmap-mdpi`, `mipmap-xhdpi`.

**Comment by varunyellina** [comment]
@ened I made a fork of this project for personal use. I've included support for MIPMAP. Since I made it for personal use, I disabled prompt for prefix. I hope that doesn't put you away.

**Comment by ened** [comment]
Thank you! Very grateful for your help.
