### ISSUE TITLE
not working in 3.3.2, not doing anything

### ISSUE THREAD

**Issue by adominomono** [GeertWille/sketch-export-assets#19]
i noticed it had:
Export iOS Assets.sketchplugin
now its:
Export iOS Assets.sketchscript

where do i put this? theres nowhere on my drive called
`~/Library/Application Support/com.bohemiancoding.sketch3/Plugins`directory

i always find it under revealer plugins anyway, but '.sketchscript', what is this?

frustrating.

installed 3.2.1 back down from 3.2.2 and still nothing. when i click 'export assets' what exactly am i suppose to see? a popup to select folder for such assets? nothing. do i select the layers, the shapes, slices, how does it work?

i think i'd be faster just using the normal export tool cos this is difficult.

**Comment by GeertWille** [comment]
@adominomono I am sorry you are confused but Sketch recently introduced a [new plugin structure](http://bohemiancoding.com/sketch/support/developer/01-introduction/03.html)... Basicly .sketchscript is a folder containing all the code within. On a mac you can right click and press show contents to see whats in it. 

How does this plugin work:
Make a selection of the layers that you want to export and then select from the menu what format you want to export too...

**Comment by GeertWille** [comment]
I updated the README.MD accordingly so now installation should be more clear.

**Comment by adominomono** [comment]
thank you Geert, sorry for the hassle, i'm a bit stupid :/ but think i have it now.
