### ISSUE TITLE
Could I customize default size assumption (MDPI) for a XHDPI for example?

### ISSUE THREAD

**Issue by ibanbe** [GeertWille/sketch-export-assets#20]

**Comment by GeertWille** [comment]
Will be adding this soon!

**Comment by ibanbe** [comment]
Yeah! I'll stay updated, thanks!!



*—Iban Beldarrain*
Graphic & UI designer
+34 685 502 251
www.ibanbeldarrain.com

2015-06-03 15:08 GMT+02:00 Geert Wille <notifications@github.com>:
