### ISSUE TITLE
Export Based on slices

### ISSUE THREAD

**Issue by bernatfortet** [GeertWille/sketch-export-assets#22]
It would be great to define the export region based on a slice, this way we can export transparent regions while seeing the boundries.

Thanks!

**Comment by varunyellina** [comment]
@bernatfortet , I faced this issue. My hack is to create rectangle with required size and then remove its fill & border. Then I group the rectangle and my icon. Exporting the group using this plugin retains the dimensions of the rectangle and its transparency. I hope it works for you.

**Comment by GeertWille** [comment]
@varunyellina that's exactly how you need to do it... Thanks for explaining! ;)

**Comment by varunyellina** [comment]
Although the plugin does an excellent job of exporting with transparency, you have to note that if your **Artboard** has _**Include in Export**_ selected along with _**Background Color**_, then your exports will no longer be transparent.
