### ISSUE TITLE
Cant seem to export

### ISSUE THREAD

**Issue by kabiruppal** [GeertWille/sketch-export-assets#23]
Cant seem to export, after it asks for input in the case of android export it doesnt seem to export the assets. Have I installed it incorrectly?

**Comment by GeertWille** [comment]
Did you select the layers you want to export?

**Comment by kabiruppal** [comment]
Yes I did, it worked with one layer yesterday when it came to Android export. Today when I tried I couldn't get it to export for Android or iOS. Maybe I have installed the plugin incorrectly. I removed and re-installed but still nothing. It's even stopped asking me for the input now.

**Comment by martinboerma** [comment]
Plugin is not showing anymore. Tried installing it via Sketch Toolbox and direct copy to Plugin folder. In both cases the plugin dies not show up in Sketch 3.3.3 (12072).

Some weird stuff is  going on with the zmalltalker plugin as well. It shows up in the plugin list but simply does not execute.

Both plugins started this weird behaviour at the same time, couple of weeks ago.

Cheers,
Martin

**Comment by GeertWille** [comment]
Mhhh I'll look into it... I know that Sketch changed his way of how plugins are packaged but I thought it would stay backwards compatible for a while...

**Comment by martinboerma** [comment]
Funny thing is that it didn't occur just after an update but in between updates. But haven't found same issue with other plugins other that zmalltalker's export plugin and yours.

**Comment by GeertWille** [comment]
@martinboerma you still have problems with the plugin?

**Comment by martinboerma** [comment]
Hi Geert, thanks for the quick response. I will apply your suggestions asap
and will report back.

Cheers,
Martin
