### ISSUE TITLE
Exported assets go full tranzparent

### ISSUE THREAD

**Issue by jansemka** [GeertWille/sketch-export-assets#24]
I installed the plugin by hand. The export works just fine all the assets will be exported but then suddenly all the assets are gone tranzparent seems like the plugin overwrite the allready exported files. I used masks to get correct sizes for all icons. It looks like when i use the masks for export the assets they will be tranzparent and the design will not appear. When I only choose the design layer itself the assets are there, but i need the masks to get proper sizes of the assets.

**Comment by GeertWille** [comment]
Does [this](https://github.com/GeertWille/sketch-export-assets/issues/22) answers your question?

**Comment by jansemka** [comment]
THX, it does. I will try it out.
