### ISSUE TITLE
While exporting the assets' bg is not transparent

### ISSUE THREAD

**Issue by sokratus** [GeertWille/sketch-export-assets#3]
I've been getting this a lot lately. Anything can be done about it?

**Comment by varunyellina** [comment]
Although the plugin does an excellent job of exporting with transparency, you have to note that if your **Artboard** has _**Include in Export**_ selected along with _**Background Color**_, then your exports will no longer be transparent.

**Comment by GeertWille** [comment]
jup correct which is normal I guess? Since you've selected include in export and have a background...

**Comment by varunyellina** [comment]
Yes, it is expected behaviour. But I didn't expect it to happen to icons in a mockup that had artboard's background.

**Comment by GeertWille** [comment]
Thank you! +1
