### ISSUE TITLE
Have slice layer, doesn't export with its bounds. 

### ISSUE THREAD

**Issue by richiesun** [GeertWille/sketch-export-assets#30]
Using Sketch 3.3.3 (12081). Not sure if bug or I'm doing something wrong. Slice layer is within group, size is bigger than icon. Clicking on Slice and using plugin, or clicking on group and using plugin results in the same export of only the icon shape, not the slice bounds.

**Comment by GeertWille** [comment]
Thanks for reporting, I fixed it...
