### ISSUE TITLE
The plugin does not appear in Sketch Plugin menu

### ISSUE THREAD

**Issue by martinboerma** [GeertWille/sketch-export-assets#31]
Hi Geert,

Using Sketch Toolbox the plugin will appear in the plugin folder but does not show in Sketch. 

Any ideas?

Running Sketch version : Version 3.3.3 (12072)

Cheers,
Martin

**Comment by GeertWille** [comment]
Hi Martin,

I tried installing it with Sketch Toolbox and it worked right out of the box so I don't know what is going wrong on your system... So let's try to solve it. 

- Can you try a clean install of the plugin with Sketch closed
- Can you open up the "Console.app" of your mac and filter it on "Sketch".
- Press the "Clear display" button so we start with a fresh screen
- now open up sketch when you are sure that the plugin is in the correct folder
- Then copy/paste the output of the "Console.app" to pastebin or something similar and post the link please so I can see or there are any errors


Thanks!
Geert

**Comment by martinboerma** [comment]
Hi Geert,

Thanks for the quick response. Your suggestions worked. Installing it with Sketch closed did it.

Cheers,
Martin

**Comment by GeertWille** [comment]
Allright!  No problem :)

**Comment by martinboerma** [comment]
Hi Geert,

With Sketch version 3.4 I have the exact same issue again. Your plugin is not showing in the plugin list. Installing it with Sketch closed does not the trick this time. Installing other plugins is no problem at all. 

Cheers,
Martin
