### ISSUE TITLE
Request for configurable export width and height

### ISSUE THREAD

**Issue by tvluong1988** [GeertWille/sketch-export-assets#33]
Hi, is there a way to configure the plugin to export user-defined size for width and height? I looked through the script and it seems to only offer scaling. Thanks.

**Comment by GeertWille** [comment]
what do you exactly mean? You can define the size of the asset by drawing an invisible rectangle?

**Comment by tvluong1988** [comment]
I have a background image at 960x640. I was hoping to modify your script to generate all the different device sizes (e.g. 1136x640, 2208x1242, 2048x1536, 1024x768), but your script only takes in only scale factor. 

I hope that makes sense.
