### ISSUE TITLE
It exports the background even if unselected

### ISSUE THREAD

**Issue by primax79** [GeertWille/sketch-export-assets#34]
while exporting an object, it exports the background even if it's not selected

scenario =>  ![sketch](https://cloud.githubusercontent.com/assets/3628678/10763221/63311894-7cc9-11e5-9c86-dc6fa95c6ca6.png)

current export => ![error_android_fun](https://cloud.githubusercontent.com/assets/3628678/10763070/d72e9786-7cc8-11e5-8ff8-ba4f519321dd.png)

expected export => ![fun](https://cloud.githubusercontent.com/assets/3628678/10763269/9b62a282-7cc9-11e5-8062-f24088959551.png)

**Comment by GeertWille** [comment]
Can you send me your (stripped) sketch file please with a dropbox link or some other service?

**Comment by alpippan** [comment]
I can confirm having the same issue on 3.3.3 and 3.4.

Can't give you any further detailed information yet, as I switched my workflow from a distinct export artboard to an in-artboard export workflow for my current project. 

At least I can also confirm it for other export plugins too -- and it might have been there for some time, which is, as far is I remember, my initial reason using a distinct export artboard.

**Comment by primax79** [comment]
try that
https://dl.dropboxusercontent.com/u/2554192/test.sketch

**Comment by GeertWille** [comment]
@alpippan actually has a good point... Here at the office we also work with an artboard called "export" and the only thing it has are all the assets grouped so you can easily export the assets that are used in the whole project. I recommend this a lot since exporting assets from out of the screen context can indeed mess up your assets big time. @primax79 I will still look into the issue although I recommend you to try and change your workflow to a distinct export artboard.

**Comment by caitlinosbahr** [comment]
I'm also having this issue – big bummer because I'm often exporting white images and creating a separate artboard (which has a white background) makes this update more inconvenient than previous versions.

**Comment by alex2web** [comment]
Same issue here :(

**Comment by igo903** [comment]
same issue too in sketch 3.4.
it' will export png with the white background. 
please help to fix it.

**Comment by narut88** [comment]
Same issue with Sketch 3.4.2

**Comment by spro77** [comment]
yes, conform... 3.4.2

**Comment by designedbyDC** [comment]
You could use this plugin while this issue is being resolved.
(https://github.com/designedbyDC/Asset-Export-for-iOS-and-Android)

**Comment by GeertWille** [comment]
Should be working again? Anyone can confirm?

**Comment by marco-duckma** [comment]
Not working for me with sketch 3.5.2
Exported assets always have solid background even if the 'background color' option is not ticked and the  checkerboard is visible in the preview toolbar.

**Comment by csky-ios** [comment]
I believe I have fixed this with pull request #56.
