### ISSUE TITLE
Hidden layers

### ISSUE THREAD

**Issue by julienpecorino** [GeertWille/sketch-export-assets#35]
Hello,
Firstly thanks for this plug-in, it's part of my workflow, without I couldn't imagine exporting all asset sizes required for Android by hand...

I have recently updated to Sketch 3.4 and since, when I select multiple assets for exporting only one stays visible and all other are hidden and not exported.

Thanks

**Comment by GeertWille** [comment]
There seems to be a lot of issues regarding the new sketch version and we (developers) didn't got notified about any breaking changes... Right now Bohemian is trying to work out why a lot of the existing plugins don't work anymore. This Friday I'll look into the problem and hope that Bohemian by that time came with a clear guide of what breaking changes they made so I can fix the issues.

Thanks for understanding :)

**Comment by GeertWille** [comment]
You still have this problem after todays update?

**Comment by julienpecorino** [comment]
No issue anymore, thanks again for this great plug-in, great work!
