### ISSUE TITLE
Intended that plugin trims transparent pixels?

### ISSUE THREAD

**Issue by martinboerma** [GeertWille/sketch-export-assets#36]
Hi,

Is it intended that the plugin trims transparent pixels?

Using Sketch 3.4 (15575)

Cheers,
Martin

**Comment by hasslunsford** [comment]
Having this issue myself. Is this resolved by newer version of Sketch?

**Comment by alex2web** [comment]
Same here :(

**Comment by cleercode** [comment]
+1. I'm pretty sure the plugin used to not do this.

**Comment by nielsbastian** [comment]
I'm not here to market other plugins, but this fork works great! :) https://github.com/designedbyDC/Asset-Export-for-iOS-and-Android

**Comment by GeertWille** [comment]
I changed the plugin as stated in the [README](https://github.com/GeertWille/sketch-export-assets/blob/master/README.md) you need to use a SliceLayer if you don't want the plugin to trim the transparant pixels...
