### ISSUE TITLE
Android assets are not exporting at correct sizes

### ISSUE THREAD

**Issue by caitlinosbahr** [GeertWille/sketch-export-assets#37]
With the "base density" setting @1x when designing at mdpi, the resulting assets are all too small – it appears to be 1/3 of the intended size. (eg. 24pt icon in sketch exports to 8px at mdpi).

**Comment by GeertWille** [comment]
Can you send me an example sketch file having this issue?

**Comment by richiesun** [comment]
Just did an uninstall and reinstall and it looks like the latest version of this plugin is exporting at bad sizes for Android @1x. Did not test iOS or windows.

**Comment by richiesun** [comment]
Played around with switching base sizes and not it seems like its working fine now. Weird.

**Comment by m4mwilco** [comment]
I had the same problem, after changing the base dpi to 1 it was fine.
The [default](https://github.com/GeertWille/sketch-export-assets/blob/master/sketch-export-assets.sketchplugin/Contents/Resources/config.json) seems to be 3.
