### ISSUE TITLE
Sketch Version 3.4.1 (15681) Export Problem

### ISSUE THREAD

**Issue by michailkouroupakis** [GeertWille/sketch-export-assets#38]
Sketch Version 3.4.1 (15681) 
Export Problem

Action/Path: Change Density->@2x->Select Android Export->Select Folder->OK 
Problem: The folder is empty with this version of sketch this plugin doesn't export anything 

Thanks for your time :)
It will be a huge time saver if you fix this issue

**Comment by GeertWille** [comment]
Anyone else has tis issue? Can you retry and pull the code see or it works now?

**Comment by michailkouroupakis** [comment]
Version 3.4.4 ---> Problem Solved
Version 3.4.1----> Problem  is still here

It is obvious that this is not plugin's problem but bohemian sketch bug

Solution: just update to latest version(for now) 3.4.4

I think sketch has a lot of bugs in the latest versions
Not so stable as in the past with bad ram usage

Thanks for your time
and sorry for false alert :(
