### ISSUE TITLE
Background export

### ISSUE THREAD

**Issue by n8mills** [GeertWille/sketch-export-assets#39]
option to not include background items with export (only layers in a group)

**Comment by designedbyDC** [comment]
You could use this plugin while this issue is being resolved.
(https://github.com/designedbyDC/Asset-Export-for-iOS-and-Android)

**Comment by nielsbastian** [comment]
Yes, this please! Plugin won't listen to the 'Export group contents only' checkbox now...

**Comment by GeertWille** [comment]
I'll add the hiding layer functionality again but the plugin will go little bit slower again then... Should work the same as "Export group contents only" only it's automatically done in code...
