### ISSUE TITLE
Hidden objects in layer groups are now ignored

### ISSUE THREAD

**Issue by iamaaronmartin** [GeertWille/sketch-export-assets#41]
I used to have a hidden box layer in a layer group that sized and aligned my assets; now it is ignored and the asset is only objects that are turned on. Is this another wonder feature in 3.4 that they didn't tell anyone about?

**Comment by GeertWille** [comment]
Is it possible to use a slice slayer instead?

**Comment by iamaaronmartin** [comment]
Do you have specs on what my layer would have to be named? I tried "slice layer" already and it's ignored as well.

**Comment by iamaaronmartin** [comment]
I see what you mean now, an actual Sketch slice. Wasn't this working without this in a previous build? I'd been successfully doing this for months without a slice layer.

**Comment by GeertWille** [comment]
@iamaaronmartin yes it was working like that before but I changed it since some people wanted to trim transparant pixels and other didn't... Normally I fixed the problem that assets underneath your asset that will be sliced is included in the export when using a "Sketch slicelayer"... Can you confirm?

**Comment by iamaaronmartin** [comment]
Using the Sketch slice layer does indeed include anything visually below the folder that is being exported.

**Comment by GeertWille** [comment]
Did you update before answering?

**Comment by iamaaronmartin** [comment]
Updated to the latest plugin. Now the whole screen goes white and nothing is exported.

**Comment by czak** [comment]
I believe I have the similar problem.

My file:

![screen shot 2016-01-08 at 10 52 16](https://cloud.githubusercontent.com/assets/14021/12195235/fa554564-b5f5-11e5-9a2d-72c842f688a5.png)

I want to export the icons **with transparent pixels intact** and I can't.
I also have a locked "Box" layer for sizing.

Tried the following:

* selecting the **artboard** - results in empty PNG files
* selecting the **slice** - results in empty PNG files
* selecting the **group** - results in trimmed PNG files, ignoring the empty Box layer

See [the .sketch file](http://images.czak.pl/icons.zip).

**Comment by GeertWille** [comment]
Mhh weird... I just noticed I had sketch 3.4.2 installed and with that it worked fined... I updated to 3.4.4 now and I'll look into it...

**Comment by gabrielsantos** [comment]
I have the same problem. I'm now forced to create a slice in every single icon (out of the box Sketch functionality).

**Comment by GeertWille** [comment]
Should be fixed now
