### ISSUE TITLE
Export Android Assets don't work

### ISSUE THREAD

**Issue by narut88** [GeertWille/sketch-export-assets#45]
Still doesn't work. No folders, no PNG. With Sketch 3.5.1.

**Comment by shahinlotfi** [comment]
I get the folders, and the files, at all relevant sizes, but the files are fully transparent / empty.

**Comment by DavidMDC** [comment]
Doing some tests, the plugin only works if the element (group, layer...) is a direct child of an _Artboard_. In other case, some layers will be hidden. The easy workaround is to drag the element as a child of the _Artboard_.

Could you solve this to use the plugin in every group or layer, level independent?

**Comment by kmh808** [comment]
Same issue here.  I try to export but get nothing.  Please try to fix, this plug-in concept is awesome and would help my team and many Sketch users, thanks!

**Comment by GeertWille** [comment]
The best way of working with this plugin is making sure you just use a "EXPORT" artboard with all assets on it and just running the plugin on that artboard.

**Comment by frankydev** [comment]
DavidMDC workaround is the only way to work with this plugin.
I tried the flow suggested by GeertWille but still doesn't work.
Great idea, please keep on this amazing job/plugin! :)

**Comment by nilsborchers** [comment]
@shahinlotfi my problem exactly.

**Comment by GeertWille** [comment]
I fixed it now... But now it becomes important that you use "asset artboards"

**Comment by csky-ios** [comment]
I have made some changes that add commands to export all exportable layers.  The changes are in pull request #56.
