### ISSUE TITLE
Export Missing 1 pixel?

### ISSUE THREAD

**Issue by VuongDung** [GeertWille/sketch-export-assets#46]
I have a background in sketch with resolution 750 & 1334  (pixel)
When i using export to IOS function
that setting base density is 1x
it export to file   bg.png with size 749x1334

Similar when export to Android

I think this is a bug

Please confirm
Thanks you

**Comment by GeertWille** [comment]
Did you try using a slice layer?

**Comment by GeertWille** [comment]
Make sure you don't use half pixels also you can use a slicer layer if you still have a problem
