### ISSUE TITLE
Exporting with transparent background

### ISSUE THREAD

**Issue by pandizajner** [GeertWille/sketch-export-assets#47]
Since some time I have a problem with exporting assets. Despite the 'Background Color > Include in export' unchecked, all the assets are exported with white background. If I do it manually, it works well, but using this plugin, assets are always placed on white space.
Is there any way to fix that?

**Comment by jairobjunior** [comment]
This is also happening on Sketch Version 3.8.1 (29687), it's actually getting whatever background color the asset is on top of.

**Comment by halol** [comment]
Have to same issue in Version 3.8.3 (29802). It merges what's below the asset you want to export.

**Comment by elsenpan** [comment]
Have same issue in Version 3.8.3 (29802).

**Comment by ntry** [comment]
Me too! So far not usable for me.

**Comment by sleeke** [comment]
Same issue in e8b6cb9. Transparency is essential for exporting assets :(

**Comment by csky-ios** [comment]
I believe I fixed this in pull request #56.
