### ISSUE TITLE
Stopped working with Sketch 3.6.1 (26313)

### ISSUE THREAD

**Issue by blynkkk** [GeertWille/sketch-export-assets#48]
Thanks for a great plugin - saved a lot of time for us!

Was working flawlessly before that
Now nothing happens when I try to use it

Could you please check it.

Thanks!

**Comment by jlorentzon** [comment]
Best plugin in my arsenal for sure. Thank you. I'm having the same problem with exporting as @blynkkk .

**Comment by GeertWille** [comment]
It's working fine on my version of sketch which is 3.6.1. Can you link me to some example sketch file? Are you selecting a layer group and not just a layer to export?

**Comment by richiesun** [comment]
Same issue here. Export isn't working. Go to export Android assets and no files show up. 3.6.1. Anybody find a workaround?

**Comment by rudacs** [comment]
Same problem

**Comment by jlorentzon** [comment]
@richiesun I don't know if this is just because you didn't save your Sketch file before you tried to export.

**Comment by richiesun** [comment]
@jlorentzon I tried a few things. Saving, uninstalling/re-installing, iOS and Android. I have an older file where the exports work. I'm working in a newer v2 file and it was outputting nothing.

**Comment by jlorentzon** [comment]
@richiesun Yeah, me too. Tried everything. Maybe time to revert back to an older version as long as it doesn't mess up my new files...

**Comment by GeertWille** [comment]
Can some of you provide me with a file that's not working?

**Comment by jlorentzon** [comment]
@GeertWille I updated the plugin (2.3) and it seems to work now. Thanks.
