### ISSUE TITLE
Export Group Contents Only

### ISSUE THREAD

**Issue by robodean** [GeertWille/sketch-export-assets#55]
It would appear that when exporting slices, the plugin does not respect if the slice is meant to export the group contents only. This is a showstopper if you have multiple groups with slices meant to only export the contents of the group the slice is in.

**Comment by blynkkk** [comment]
+1
@GeertWille, thanks for such a helpful plugin!

Unfortunately I'm only capable of correct exporting from symbols page. Otherwise your plugin always exports assets with background, no matter what I do.

Please fix it when you can. 

Thanks.

**Comment by GeertWille** [comment]
@blynkkk make sure to opt-in for the beta on [sketchexporter.co](sketchexporter.co). This new plugin is based on this one and has a lot of improvements.

**Comment by csky-ios** [comment]
I believe I have fixed this with pull request #56.
