### ISSUE TITLE
Not able to export any slice and missing docs

### ISSUE THREAD

**Issue by ronaldo-getreveel** [GeertWille/sketch-export-assets#61]
I'm not able to export any slice or group using the new version. No error are being shown. 

I'm using sketch 41 and SketchExporter 0.3.2. 

And there is no documentation about on how to use the plugin. Creating slices and grouping them and exporting the group are not possible. 
I discovered that I must create a page called "slices" and a artboard named "jpg" or "png". 

There is no documentation in http://sketchexporter.co/

Regards.

**Comment by annawchou** [comment]
i'm also having the same issues too. i try to export and no files show up anywhere after i upgraded to the latest sketch (41.4) i've been trying to export artboards like i have before and now it has stopped working. :/

**Comment by GeertWille** [comment]
I don't think you got access to the beta did you? We send our beta users an email on how to use the plugin. Let me know with what email you signed up and maybe I can give you access as well.

**Comment by ronaldo-getreveel** [comment]
Yes I did.  Check the email  rrigoni at gmail. 

I'm using the beta version but it still not working.

**Comment by GeertWille** [comment]
I send you a mail...
