### ISSUE TITLE
Export stopped working

### ISSUE THREAD

**Issue by hanneskl** [GeertWille/sketch-export-assets#64]
I can select the folder where the files should go and hit "Open". 

But no files get exported.

Used to work until a few days ago. Not sure, if related to an OS or Sketch Update.

Sketch 41.2
MacOS Sierra 10.12.1

**Comment by emieldehaan** [comment]
Same here. Everything working one moment, everything stopped working the other. Did not update any component.

Folders get created, but folders remain empty.

Sketch 41.2
MacOS 10.12.1

**Comment by GeertWille** [comment]
Weird, I'm using the same OS and Sketch version and everything seems to be working... Can you describe more in depth what's not working? Is it iOS export? Android export? ... Can you provide me a link to an example sketch file that doesn't seem to be working?

**Comment by Adam-CS** [comment]
Same here, plugin says the slices have been exported but nothing seems to have happened.

Sketch 41.2 (35397)
MacOS 10.12.1

I quickly put toghether this sketch file that doesn't work as well:
https://dl.dropboxusercontent.com/u/58724361/Example%20Export.sketch

Thanks!

**Comment by GeertWille** [comment]
Weird... For me it perfectly works. Can you check the log for any errors?
Follow the steps under [Reporting Bugs](https://www.sketchapp.com/support/faq/) and send me the output into a dropbox link please :)

**Comment by hanneskl** [comment]
[sketch.logs.txt](https://github.com/GeertWille/sketch-export-assets/files/664678/sketch.logs.txt)

**Comment by mustafaerturk** [comment]
Same issue. Asset folder created but exported image folders empty. 

Sketch --> 41 (35326)
MacOS --> 10.12.2

**Comment by GeertWille** [comment]
thanks @hanneskl but I forgot that in the new mac os the console has been changed. Can you look for this file and attach this instead please? 

Try to remove it at first then use the plugin and then send it to me so I don't have to go through a whole lot of data 👍 

`/Users/<username>/Library/Logs/com.bohemiancoding.sketch3/Plugin Output.log`

**Comment by hanneskl** [comment]
Is empty. 
![screen shot 2016-12-27 at 15 24 53](https://cloud.githubusercontent.com/assets/711168/21501491/ad90d5bc-cc48-11e6-8ed5-eebc7331a8b1.png)

I tried exporting just minutes before...

**Comment by emieldehaan** [comment]
If it helps: I found (maybe part of) the problem. If I select the baseline to @1x, exporting works just fine. If I set it to @2x, however, assets are not exported.

**Comment by GeertWille** [comment]
@emieldehaan surely helps... I'll look into it tonight!

**Comment by GeertWille** [comment]
Should be fixed...
