### ISSUE TITLE
Only exports to the same folder as the source file

### ISSUE THREAD

**Issue by davidklaw** [GeertWille/sketch-export-assets#9]
It seems to be doing this regardless of where I ask it to export to.

**Comment by tripr** [comment]
same issue here

**Comment by aalok8922** [comment]
Same. It doesn't let me choose where I want the assets to save...
Doesn't even bring up a dialog

**Comment by davidklaw** [comment]
@aalok8922 It requires that the file you're exporting from be saved first. If it's not you won't see a dialog or any sort of error message.

**Comment by davidklaw** [comment]
I'm just sort of glancing through the code here but it looks like the file chooser isn't functional. The script saves the file's current working directory, asks the user for the directory of their choosing, but then goes ahead and saves processed slices to the current working directory.

**Comment by aalok8922** [comment]
Is there a fix to this?

Still not working. I saved my file and ran the plugin. Still no prompt. I checked the directory of where my file is saved: nothing there.

**Comment by davidklaw** [comment]
@aalok8922 Open up Console.app and filter it for "sketch". If an exception is occurring you should see it there. Let us know what you see. Something like:

![image](https://cloud.githubusercontent.com/assets/467443/6312637/e7c80bb6-b94d-11e4-9028-94a6df170221.png)

**Comment by aalok8922** [comment]
The last 3 lines:
![image](https://cloud.githubusercontent.com/assets/10872275/6312665/1fef75be-b94f-11e4-98cd-3f05b0e01735.png)

**Comment by davidklaw** [comment]
@aalok8922 Expand that exception there at the end

**Comment by aalok8922** [comment]
@davidklaw hmm, looks like the source url is funky? Thanks for your help, by the way.

![image](https://cloud.githubusercontent.com/assets/10872275/6312740/6640e144-b952-11e4-8ef0-062b1f0ed5d7.png)

**Comment by aalok8922** [comment]
I think I fixed the directory issue, but still getting the same result:
![image](https://cloud.githubusercontent.com/assets/10872275/6312761/851e49fc-b953-11e4-8fb8-62688a1d7baa.png)

**Comment by davidklaw** [comment]
You might want to try downloading the plugin again and throwing a fresh copy of it in there.

**Comment by GeertWille** [comment]
I'll try to fix this issue this week!

**Comment by GeertWille** [comment]
Normally this issue has been fixed. Seems like I already has fixed it but didn't put it on here...

**Comment by davidklaw** [comment]
Thanks @GeertWille :+1:
